//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicomStorage.WindowsService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104")]
        public int Port {
            get {
                return ((int)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\DICOM\\Хранилище")]
        public string StorageBaseDir {
            get {
                return ((string)(this["StorageBaseDir"]));
            }
            set {
                this["StorageBaseDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\DICOM\\Импорт")]
        public string ImportBaseDir {
            get {
                return ((string)(this["ImportBaseDir"]));
            }
            set {
                this["ImportBaseDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfServerOptions xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <ServerOptions>
    <ServerName>FLUO</ServerName>
    <StorageDir>Флюорография</StorageDir>
    <ImportDir>Флюорография</ImportDir>
    <ActionName>Флюорография</ActionName>
    <Codepage>1251</Codepage>
  </ServerOptions>
  <ServerOptions>
    <ServerName>MAMMO</ServerName>
    <StorageDir>Маммография</StorageDir>
    <ImportDir>Маммография</ImportDir>
    <ActionName>Маммография</ActionName>
    <Codepage>0</Codepage>
  </ServerOptions>
  <ServerOptions>
    <ServerName>RENTGEN</ServerName>
    <StorageDir>Рентген</StorageDir>
    <ImportDir>Рентген</ImportDir>
    <ActionName>Рентген</ActionName>
    <Codepage>0</Codepage>
  </ServerOptions>
</ArrayOfServerOptions>")]
        public global::DicomStorage.WindowsService.ServerOptionsList OptionsList {
            get {
                return ((global::DicomStorage.WindowsService.ServerOptionsList)(this["OptionsList"]));
            }
            set {
                this["OptionsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>DicomCatalog</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection QueueNameList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QueueNameList"]));
            }
            set {
                this["QueueNameList"] = value;
            }
        }
    }
}
